// <auto-generated />
using System;
using Candles.Repositories.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Candles.Repositories.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200314145405_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("candles")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Candles.Repositories.Entities.CandleEntity", b =>
                {
                    b.Property<string>("AssetPairId")
                        .HasColumnName("asset_pair_id")
                        .HasColumnType("varchar(36)");

                    b.Property<short>("Type")
                        .HasColumnName("type")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Time")
                        .HasColumnName("time")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double>("Close")
                        .HasColumnName("close")
                        .HasColumnType("double precision");

                    b.Property<double>("High")
                        .HasColumnName("high")
                        .HasColumnType("double precision");

                    b.Property<double>("Low")
                        .HasColumnName("low")
                        .HasColumnType("double precision");

                    b.Property<double>("Open")
                        .HasColumnName("open")
                        .HasColumnType("double precision");

                    b.HasKey("AssetPairId", "Type", "Time");

                    b.ToTable("candles");
                });
#pragma warning restore 612, 618
        }
    }
}
